### ISSUE TITLE
exiting

### ISSUE THREAD

**Issue by serunos** [a2br/notes-ed#2]
When you launch the program directly from the program file. You can connect but as soon as the grades are collected the window's program kill.
//
Quand on lance le programme directement depuis le fichier. On peut se connecter mais dès que les notes sont chargées le programme se ferme. On a pas le temps de consulter les notes.
Sacha^^

**Comment by a2br** [comment]
Salut,
ça a déjà été patch dans f774a5c2505e3a2e1b2cb32033a8939a588afc6b
https://github.com/a2br/notes-ed/blob/f774a5c2505e3a2e1b2cb32033a8939a588afc6b/main.py#L170-L171
un `git pull` suffira pour mettre à jour
