### ISSUE TITLE
"Stop Iteration"

### ISSUE THREAD

**Issue by ghost** [a2br/notes-ed#9]
Bonjour !
Tout d'abord merci pour ce projet c'est super !
Cependant, lorsque je rentre mon mdp quelques secondes plus tard j'ai cette erreur. 
```
  File "C:\Program Files (x86)\Spyder\WPy64-3740\scripts\notes-ed-main\main.py", line 70, in select_account
    str(account['id']) == choice[0:4]), e_accounts))

StopIteration
```

Voila ! Merci encore et bon courage !

**Comment by a2br** [comment]
Merci pour avoir signalé ce problème! Normalement, https://github.com/a2br/notes-ed/commit/52a72b1681a161d4354c257ce0482d8379f66ab9 devrait remettre les choses en ordre. Je suis assez étonné que cette erreur survienne... Dis-moi si ton problème est réglé. `git pull` pour mettre à jour.

Dans tous les cas, est-ce que tu pourrais partager des infos de debug? Par exemple, les valeurs de `accounts`, `e_accounts`, `choices` et de `choice` ? Les réponses d'EcoleDirecte peuvent être incertaines. Si tu acceptes, n'hésite pas a masquer les données sensibles concernant ton compte ED. Normalement, des `print` dans l'emplacement ci-dessous feraient l'affaire. Merci.
https://github.com/a2br/notes-ed/blob/52a72b1681a161d4354c257ce0482d8379f66ab9/main.py#L68
